/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "STM32f407xx.h"
#include <stdint.h>
#include "stm32f407xx_gpio_driver.h"

void delay(void){
	for(uint32_t i=0;i<400000/2;i++);
}
void EXTI0_IRQHandler(void){
	delay();
	GPIO_ToggleOutputPin(GPIOD, 15);
	GPIO_IRQHandling(0);
}
int main(void)
{
	/////////////////////////
	GPIO_Handle_t GpioLed;
	GpioLed.pGPIOx=GPIOD;
	GpioLed.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_15;
	GpioLed.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_OUT;
	GpioLed.GPIO_PinConfig.GPIO_PinOPType=GPIO_PIN_OP_PP;
	GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl=GPIO_PINR_NO_PUPD;
	GpioLed.GPIO_PinConfig.GPIO_PinSpeed=GPIO_SPEED_FAST;
	////////////////////////////////////
	GPIO_Handle_t GpioBtn;
	GpioBtn.pGPIOx=GPIOA;
	GpioBtn.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_0;
	GpioBtn.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_IT_RT;
	GpioBtn.GPIO_PinConfig.GPIO_PinPuPdControl=GPIO_PINR_NO_PUPD;
	GpioBtn.GPIO_PinConfig.GPIO_PinSpeed=GPIO_SPEED_FAST;
	///////////////////////
	GPIO_PClk_Control(GpioLed.pGPIOx,ENABLE);
	GPIO_PClk_Control(GpioBtn.pGPIOx,ENABLE);
	GPIO_Init(&GpioLed);
	GPIO_Init(&GpioBtn);
	GPIO_IRQConfing(IRQ_NO_EXTI0, ENABLE);
    /* Loop forever */
	for(;;);
}
